### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Fuwiz** [K1nGsmaN-hub/ranobelib-parser#1]
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (C:\Users\user\Desktop\ranobelib-parser-master\node_modules\epub-gen\lib\index.js:169:42)
    at exports.each (C:\Users\user\Desktop\ranobelib-parser-master\node_modules\cheerio\lib\api\traversing.js:300:24)
    at C:\Users\user\Desktop\ranobelib-parser-master\node_modules\epub-gen\lib\index.js:159:18
    at Function.map (C:\Users\user\Desktop\ranobelib-parser-master\node_modules\underscore\underscore-node-f.cjs:1342:22)
    at new EPub (C:\Users\user\Desktop\ranobelib-parser-master\node_modules\epub-gen\lib\index.js:95:32)
    at BookService.generateEpubFromData (C:\Users\user\Desktop\ranobelib-parser-master\build\services\BookService\index.js:101:16)
    at C:\Users\user\Desktop\ranobelib-parser-master\build\index.js:50:45
    
    

До этого качал другие и всё было нормально
Ошибка с https://ranobelib.me/phenomeno-mitsurugi-yoishi-wa-kowaganai

**Comment by Harurunya** [comment]
точно такая же ошибка

Генерация книги i-sekai-ni-otosareta.epub в папке books/

S:\ranobelib-parser-master\node_modules\epub-gen\lib\index.js:169
            mediaType = mime.getType(url.replace(/\?.*/, ""));
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (S:\ranobelib-parser-master\node_modules\epub-gen\lib\index.js:169:42)
    at exports.each (S:\ranobelib-parser-master\node_modules\cheerio\lib\api\traversing.js:300:24)
    at S:\ranobelib-parser-master\node_modules\epub-gen\lib\index.js:159:18
    at Function.map (S:\ranobelib-parser-master\node_modules\underscore\underscore-node-f.cjs:1342:22)
    at new EPub (S:\ranobelib-parser-master\node_modules\epub-gen\lib\index.js:95:32)
    at BookService.generateEpubFromData (S:\ranobelib-parser-master\build\services\BookService\index.js:101:16)
    at S:\ranobelib-parser-master\build\index.js:50:45

Node.js v21.1.0
Для продолжения нажмите любую клавишу . . .

качалась
https://ranobelib.me/i-sekai-ni-otosareta
а так же 
https://ranobelib.me/tsuki-ga-michibiku-isekai-douchuu-novel
 в обоих случаях одна и та же ошибка генерации.

**Comment by Harurunya** [comment]
восстановление Node.js через repair в установщике
и последующее повторное копирование репозитория парсера в другое место дает точно такой же результат

Генерация книги i-sekai-ni-otosareta.epub в папке books/

S:\1\node_modules\epub-gen\lib\index.js:169
            mediaType = mime.getType(url.replace(/\?.*/, ""));
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (S:\1\node_modules\epub-gen\lib\index.js:169:42)
    at exports.each (S:\1\node_modules\cheerio\lib\api\traversing.js:300:24)
    at S:\1\node_modules\epub-gen\lib\index.js:159:18
    at Function.map (S:\1\node_modules\underscore\underscore-node-f.cjs:1342:22)
    at new EPub (S:\1\node_modules\epub-gen\lib\index.js:95:32)
    at BookService.generateEpubFromData (S:\1\build\services\BookService\index.js:101:16)
    at S:\1\build\index.js:50:45

Node.js v21.1.0
Для продолжения нажмите любую клавишу . . .

**Comment by banditto9** [comment]
Добрый день, благодарю за труды - единственный работающий парсер, причем выпекает epub сразу отличного качества - с главами и обложкой!

К сожалению, на части тайтлов есть ошибка, как у коллег выше. В Windows10 22H2 и в Дебиан 12.2 одинаково, причем только на некоторых ранобэ, но их явно больше половины.
Хром запускается, листает, парсит главы, валится уже ближе к концу.

npm start
Здравствуйте, это программа загрузки книг с сайта ranobelib.me
Пожалуйста, прочитайте информацию ниже.

Во время загрузки у Вас, несколько раз, будет открываться и закрываться окно браузера.
Пожалуйста, не беспокойтесь, так и должно быть.
Во время загрузки, пожалуйста, не трогайте окно браузера, это может привести к сбоям.

Введите, пожалуйста, адрес книги с сайта ranobelib.me
Пример адреса: https://ranobelib.me/sakurasou-no-pet-na-kanojo-novel
Пожалуйста, указывайте верный адрес, во избежания проблем с работой программы.
https://ranobelib.me/chaosgate

Сейчас начнется загрузка книги, по адресу: https://ranobelib.me/chaosgate

Получение информации о книге...

Получение списка глав...

Загрузка всех глав книги, поочередно...

Генерация книги chaosgate.epub в папке books/

/home/archie/tools/ranobelib-parser/node_modules/epub-gen/lib/index.js:169
            mediaType = mime.getType(url.replace(/\?.*/, ""));
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (/home/archie/tools/ranobelib-parser/node_modules/epub-gen/lib/index.js:169:42)
    at exports.each (/home/archie/tools/ranobelib-parser/node_modules/cheerio/lib/api/traversing.js:300:24)
    at /home/archie/tools/ranobelib-parser/node_modules/epub-gen/lib/index.js:159:18
    at Function.map (/home/archie/tools/ranobelib-parser/node_modules/underscore/underscore-node-f.cjs:1342:22)
    at new EPub (/home/archie/tools/ranobelib-parser/node_modules/epub-gen/lib/index.js:95:32)
    at BookService.generateEpubFromData (/home/archie/tools/ranobelib-parser/build/services/BookService/index.js:101:16)
    at /home/archie/tools/ranobelib-parser/build/index.js:50:45

Node.js v18.13.0

**Comment by K1nGsmaN-hub** [comment]
Привет всем кто описался! Спасибо Вам! Ошибка связана с библиотекой конвертора текста в epub. Откатил и вынес тайпскрпт версию в отдельную ветку, так что прошу, обновите свои версии, до текущей в master :)
Сейчас такой ошибки больше не должно быть.
